name: Build and Rollout Pipeline

on: 
  workflow_dispatch: 
    inputs:
      build:
        description: 'NPM build and test'
        type: boolean
        required: true
        default: true
      deploy:
        description: 'Deploy'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build And Test
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install all dependencies
        run: npm install --legacy-peer-deps
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        env:
          VITE_EMAIL_SERVICE_ID: ${{ secrets.VITE_EMAIL_SERVICE_ID }}
          VITE_EMAIL_TEMPLATE_ID: ${{ secrets.VITE_EMAIL_TEMPLATE_ID }}
          VITE_EMAIL_PUBLIC_KEY: ${{ secrets.VITE_EMAIL_PUBLIC_KEY }}
        run: npm run build

      - name: Test
        run: npm run test

      - name: Zip files
        run: zip -r build.zip build

      - name: Deploy application
        run: |
          curl -X POST ${{ secrets.HOSTINGER_WEBHOOK_URL }} \
          -F "file=@build.zip"


 
