name: Build and Rollout Pipeline

on: 
  push:
    branches:
      - main
  workflow_dispatch: 
    inputs:
      build:
        description: 'NPM build, test and deploy'
        type: boolean
        required: true
        default: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build And Test
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install all dependencies
        run: npm install --legacy-peer-deps
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        env:
          VITE_EMAIL_SERVICE_ID: ${{ secrets.VITE_EMAIL_SERVICE_ID }}
          VITE_EMAIL_TEMPLATE_ID: ${{ secrets.VITE_EMAIL_TEMPLATE_ID }}
          VITE_EMAIL_PUBLIC_KEY: ${{ secrets.VITE_EMAIL_PUBLIC_KEY }}
        run: npm run build

      - name: Test
        run: npm run test

      - name: Zip files
        run: zip -r build.zip build

      - name: Configure SSH key
        run: |
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Add Hostinger to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.HOSTINGER_SSH_PORT }} ${{ secrets.HOSTINGER_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Verificar build.zip
        run: ls -lh build.zip
      
      - name: Testar conexão SSH
        run: |
          ssh -p ${{ secrets.HOSTINGER_SSH_PORT }} -i id_rsa \
            ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} "echo 'Conexão OK'"
      - name: Deploy application
        run: |
          set -e
          scp -P ${{ secrets.HOSTINGER_SSH_PORT }} build.zip ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }}:${{ secrets.HOSTINGER_DEPLOY_PATH }}

      - name: Unzip build.zip in the server
        run: |
          ssh -p ${{ secrets.HOSTINGER_SSH_PORT }} -i id_rsa \
            ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} \
            "unzip -o ${{ secrets.HOSTINGER_DEPLOY_PATH }}/build.zip -d ${{ secrets.HOSTINGER_DEPLOY_PATH }}"
